// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoList.Api.Data;

#nullable disable

namespace TodoList.Api.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    partial class TodoListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoList.Api.Features.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreationIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("creation_idempotency_key");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_tasks_completed_at")
                        .HasFilter("status = 'completed'");

                    b.HasIndex("CreationIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_tasks_creation_idempotency_key");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_tasks_status_created_at");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_completion", "(status = 'completed' AND completed_at IS NOT NULL) OR (status <> 'completed' AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_tasks_description_length", "description IS NULL OR char_length(description) <= 10000");

                            t.HasCheckConstraint("ck_tasks_priority", "priority IN ('none', 'low', 'medium', 'high', 'urgent')");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('not_started', 'in_progress', 'blocked', 'completed')");

                            t.HasCheckConstraint("ck_tasks_title_length", "char_length(title) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("ck_tasks_updated_at", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("TodoList.Api.Features.Tasks.TaskStatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_task_status_events");

                    b.HasIndex("TaskId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_task_status_events_task_occurred_at");

                    b.ToTable("task_status_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_status_events_changed", "from_status <> to_status");

                            t.HasCheckConstraint("ck_task_status_events_from_status", "from_status IN ('not_started', 'in_progress', 'blocked', 'completed')");

                            t.HasCheckConstraint("ck_task_status_events_to_status", "to_status IN ('not_started', 'in_progress', 'blocked', 'completed')");
                        });
                });

            modelBuilder.Entity("TodoList.Api.Features.Tasks.TaskStatusEvent", b =>
                {
                    b.HasOne("TodoList.Api.Features.Tasks.TaskItem", "Task")
                        .WithMany("StatusEvents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_status_events_tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TodoList.Api.Features.Tasks.TaskItem", b =>
                {
                    b.Navigation("StatusEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
